
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-11.4}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-stock_project}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD:-1}
      MARIADB_USER: ${MARIADB_USER:-stock_app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-stock_app}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
